# Generated by Django 5.1 on 2024-08-18 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='project_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('summary', models.CharField(max_length=500)),
                ('collaborators', models.CharField(max_length=120)),
                ('deployed_site', models.CharField(max_length=2048)),
                ('github_repo', models.CharField(max_length=2048)),
                ('reflections', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('favourite', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('project_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='emoji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('engagement', models.IntegerField(default=0)),
                ('emojis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project_detail')),
            ],
        ),
    ]
