# Generated by Django 5.1 on 2024-08-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emoji',
            name='fontawesome_classname',
            field=models.CharField(choices=[('fa-regular fa-thumbs-up', 'thumbs-up'), ('fa-regular fa-heart', 'heart'), ('fa-regular fa-face-smile', 'face-smile'), ('fa-regular fa-face-grin-stars', 'face-grin-stars'), ('fa-regular fa-regular fa-face-grin-hearts', 'face-grin-hearts'), ('fa-regular fa-face-grin-beam', 'face-grin-beam'), ('', 'unselected')], default='', max_length=50),
        ),
    ]
