# Generated by Django 5.1 on 2024-08-18 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_emoji_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_detail',
            old_name='project_details',
            new_name='account',
        ),
        migrations.RemoveField(
            model_name='emoji',
            name='project',
        ),
        migrations.AddField(
            model_name='emoji',
            name='account',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
